Кошара Павел
urfu-2016/javascript-task-7 pull request #4
Opened 2016-11-18 08:55 UTC by melanholy

тысяча и одно имя для переменной друга

2016-11-18 08:56 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 24

2016-11-18 09:59 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2016-11-18 10:37 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2016-11-18 15:15 UTC, mironov-alexey commented
🚀

2016-11-19 09:30 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2016-11-19 17:33 UTC, Vittly requested changes
пара замечаний, нужно поправить
🍅

2016-11-19 17:33 UTC, Vittly commented on lib.js
> +        return friendWithLevel.friend.best || false;
`level > 0` ?

2016-11-19 17:33 UTC, Vittly commented on lib.js
> +                friendWithLevel.friend.friends.forEach(function (friendName) {
аж три цикла: `while`, `reduce` и `forEach` - можно сократить до двух - `while` и `forEach`. И сразу станет больше походить на классический поиск в ширину

2016-11-19 17:33 UTC, Vittly commented on lib.js
> +        throw new TypeError();
а текст? Мы же программу пишем, а не удовлетворяем требованием тестов:)

2016-11-19 17:33 UTC, Vittly commented on lib.js
> +LimitedIterator.prototype.constructor = LimitedIterator;
поидее лишнее действие, которое ни на что не повлияет

2016-11-19 17:33 UTC, Vittly commented on lib.js
> +    this._filters = [];
кмк внутри должна быть просто функция, зачем массив? По задаче это не нужно

2016-11-19 17:38 UTC, melanholy commented on lib.js
> +    this._filters = [];
Это я попытался сделать что-то осмысленное из затеи с наследованием фильтров. Тупое переопределение единственного метода я счел бессмысленным. Теперь я кажется понял, что цель была в том чтобы работал `instanceof Filter`

2016-11-19 17:40 UTC, melanholy commented on lib.js
> +LimitedIterator.prototype.constructor = LimitedIterator;
вроде считается хорошим тоном

2016-11-19 18:22 UTC, melanholy commented on lib.js
> +                friendWithLevel.friend.friends.forEach(function (friendName) {
Очередь применить? Свою делать по-моему оверхед, а на массивах shift будет за О(n). Или я неправильно понял?

2016-11-19 18:48 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2016-11-19 18:52 UTC, melanholy commented
🍏 
поиск все равно не классический из-за отсутствия быстрой очереди, но кол-во циклов было сокращено

2016-11-20 11:14 UTC, Vittly commented on lib.js
> +    var addNextLevelFriend = function (friendName) {
можно было сделать и `function declaration`, ну да неважно

2016-11-20 11:16 UTC, Vittly commented on lib.js
> +        }
можно было обойтись одной очередью, а текущую вложенность получать не из глобальной переменной, а из `level`-а текущего френда

2016-11-20 11:16 UTC, Vittly commented on lib.js
> +        }
сейчас еще есть избыточность

2016-11-20 11:18 UTC, Vittly commented on lib.js
>  }
функции `getTrue`, `isMale`, `isFemale` я бы сложил в какой-то хешик типа `filters = { getTrue : ... }` - типа модуль - чтоб функции отдельно не болтались

2016-11-20 11:19 UTC, Vittly approved these changes

2016-11-20 11:20 UTC, Vittly commented
Надо бы перезалить наверное - а то travis сломался - чтоб проверки прогнать
:tomato:

2016-11-20 11:21 UTC, melanholy commented on lib.js
> +        }
очередью какой? на массивах будет медленно, а свою делать кажется лишним

2016-11-20 11:36 UTC, Vittly commented on lib.js
> +        }
на массивах - да медленно, но для наших объемов норм.

А зачем настоящая очередь? Какая разница в каком порядке обходить? Можно и задом наперед - разве нет?

2016-11-20 11:39 UTC, melanholy commented on lib.js
> +        }
А куда вытащенные результаты девать? Класть их в начало `currentLevelFriends` тоже медленно, а в конец нельзя, потому что получится поиск в ширину

2016-11-20 11:49 UTC, melanholy commented on lib.js
> +    var addNextLevelFriend = function (friendName) {
проблема в том, что придется с собой тащить все перемнные из замыкания. можно через thisArg в forEach, но тогда будет линтер жаловаться на unexpected 'this'

2016-11-20 15:51 UTC, Vittly commented on lib.js
> +    var addNextLevelFriend = function (friendName) {
мм, ну да, так плохо

2016-11-20 15:52 UTC, Vittly commented on lib.js
> +        }
ага, а какая разница какой поиск? Нигде не сказано какой порядок обхода должен быть

2016-11-20 16:02 UTC, melanholy commented on lib.js
> +        }
поиск в глубину неверно расставит круги. простая ситуация: Sam - лучший друг, знает John и Lisa. John знает Lisa. Поиск в глубину может пойти так: Sam(1 уровень) -> John(2 уровень) -> Lisa(3 уровень). Это, очевидно, неверно

2016-11-20 16:12 UTC, Vittly commented on lib.js
> +        }
Ну да, ты прав

2016-11-20 16:14 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2016-11-20 16:14 UTC, Vittly commented
Все норм, молодец!

2016-11-20 16:14 UTC, closed without merging