Трушков Валерий
urfu-2016/javascript-task-7 pull request #41
Opened 2016-12-07 18:28 UTC by flafla

2016-12-07 18:28 UTC, honest-hrundel commented
:tomato: Пройдено тестов 3 из 24

2016-12-07 18:36 UTC, honest-hrundel commented
:tomato: Пройдено тестов 3 из 24

2016-12-07 18:42 UTC, honest-hrundel commented
:tomato: Пройдено тестов 21 из 24

2016-12-07 18:52 UTC, honest-hrundel commented
:tomato: Пройдено тестов 21 из 24

2016-12-07 19:01 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2016-12-07 19:03 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2016-12-08 20:45 UTC, Dodo888 commented on lib.js
> +    return this.currentDepth === this.friends.length;
❗️ Это итератор, а не глубина

2016-12-08 20:45 UTC, Dodo888 commented on lib.js
> +            return friend.level > 0 && friend.level < MAX_DEPTH && filter.apply(friend);
❗️ `apply` - название встроенной функции. Эту функцию лучше назвать по-другому.

2016-12-08 20:47 UTC, Dodo888 commented on lib.js
> +function extend(Child, Parent) {
❗️ Из этого метода достаточно оставить 2 строки

2016-12-08 20:48 UTC, Dodo888 commented
Хорошее решение. Интересная идея обхода графа друзей. Оставил маленькие замечания

2016-12-08 20:48 UTC, Dodo888 commented
🍅

2016-12-09 13:01 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2016-12-10 07:47 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2016-12-11 17:30 UTC, Dodo888 commented on lib.js
> +var MAX_DEPTH = 99999999;
В js есть встроенная константа для максимально возможного значения - Number.MAX_VALUE

2016-12-11 17:30 UTC, Dodo888 commented on lib.js
> +        subFriend.level = Math.min(subFriend.level, friend.level + 1, currentIndex);
Кажется, мы потеряем свойство `level`, если оно будет у переданного объекта

2016-12-11 17:30 UTC, Dodo888 commented
🚀

2016-12-12 05:40 UTC, flafla commented on lib.js
> +        subFriend.level = Math.min(subFriend.level, friend.level + 1, currentIndex);
не, не должны

2016-12-12 09:34 UTC, mokhov requested changes
🍅

2016-12-12 09:34 UTC, mokhov commented on lib.js
> +    friend.friends.sort().forEach(function (friendName) {
А зачем здесь sort?

2016-12-12 09:34 UTC, mokhov commented on lib.js
> +            return first.level > second.level ? 1 : -1;
`Math.sign(first.level-second.level)`

2016-12-12 09:34 UTC, mokhov commented on lib.js
> +Iterator.prototype.done = function () {
Зачем нужно выносить это в отдельную функцию?

2016-12-12 09:34 UTC, mokhov commented on lib.js
> +    return this.comparator.apply(null, arguments);
Зачем здесь так сложно сделано, почему нельзя реагировать на переданные аргументы и если их нет, то возвращать `true?

2016-12-12 09:34 UTC, mokhov commented on lib.js
> +    if (!(filter instanceof Filter)) {
Почему filter является объектом, а не функцией?

2016-12-12 09:34 UTC, mokhov commented on lib.js
> +        indexedFriends[friend.name] = friend;
Строка выше не используется в данной строке, но строкой ниже снова условие на `friend.best`, можно перегруппировать и написать функцию лаконичнее, тем более что объекты передаются по ссылке

2016-12-12 17:34 UTC, flafla commented on lib.js
> +    friend.friends.sort().forEach(function (friendName) {
> Обход всегда идет в алфавитном порядке имен
только из этих побуждений впилил, а так то он не нужен

2016-12-12 17:37 UTC, flafla commented on lib.js
> +Iterator.prototype.done = function () {
> Итератор должен иметь два метода: done() и next()

или ты про что?

2016-12-12 17:42 UTC, flafla commented on lib.js
> +    return this.comparator.apply(null, arguments);
как не будет аргументов, если я фильтрую друзей и каждого друга передаю в фильтр?

2016-12-12 17:52 UTC, flafla commented on lib.js
> +    if (!(filter instanceof Filter)) {
потому что `filter` должен быть инстансом `Filter` созданным функцией конструктором через `new`, а инстанс это объект.

2016-12-13 08:33 UTC, mokhov commented on lib.js
> +Iterator.prototype.done = function () {
Хм... ок

2016-12-13 11:40 UTC, honest-hrundel commented
:tomato: Пройдено тестов 21 из 24

2016-12-13 11:44 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2016-12-13 11:45 UTC, flafla commented on lib.js
> +    friend.friends.sort().forEach(function (friendName) {
ан ннет, без сорта то три теста падает.

2016-12-13 11:49 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 24 из 24

2016-12-13 12:58 UTC, closed without merging